spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pickbook_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:"PickBookSuperSecretKeyThatShouldBe256BitsLongForSecurity!!"}
  expiration: 86400000
  refresh-expiration: 604800000

cors:
  allowed-origins: ${FRONTEND_URL:"http://localhost:5173"}